import React, { useState, useEffect } from 'react';
import { Layers, Box, Briefcase, FileText } from 'lucide-react';
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import DashboardCard from '../components/DashboardCard';
import Table from '../components/Table';
import Loader from '../components/Loader';
import { getAllCategories } from '../services/categoryService';
import { getAllResources } from '../services/resourceService';
import { getAllProjects } from '../services/projectService';
import { getAllReports } from '../services/reportService';

const COLORS = ['#0c4a34', '#166534', '#15803d', '#16a34a', '#22c55e', '#4ade80', '#86efac', '#bbf7d0'];

const Dashboard = () => {
  const [stats, setStats] = useState({
    categories: 0,
    resources: 0,
    projects: 0,
    reports: 0
  });
  const [recentReports, setRecentReports] = useState([]);
  const [chartData, setChartData] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchDashboardData = async () => {
      setLoading(true);
      try {
        const [categories, resources, projects, reports] = await Promise.all([
          getAllCategories(),
          getAllResources(),
          getAllProjects(),
          getAllReports()
        ]);

        setStats({
          categories: categories.length,
          resources: resources.length,
          projects: projects.length,
          reports: reports.length
        });

        // Get 5 most recent reports
        const sortedReports = reports.sort((a, b) => new Date(b.reportDate) - new Date(a.reportDate));
        setRecentReports(sortedReports.slice(0, 5));

        // Group resources by category for chart
        const grouped = resources.reduce((acc, resource) => {
          const catName = resource.category?.categoryName || 'Unknown';
          if (!acc[catName]) acc[catName] = 0;
          acc[catName]++;
          return acc;
        }, {});

        const dataForChart = Object.keys(grouped).map(key => ({
          name: key,
          value: grouped[key]
        }));
        
        setChartData(dataForChart);

      } catch (error) {
        console.error("Failed to load dashboard data:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchDashboardData();
  }, []);

  const reportColumns = [
    { header: 'Type', accessor: 'reportType' },
    { header: 'Project', accessor: 'project', render: (row) => row.project?.projectName || 'N/A' },
    { header: 'Date', accessor: 'reportDate', render: (row) => new Date(row.reportDate).toLocaleDateString() },
    { header: 'Generated By', accessor: 'generatedBy', render: (row) => row.generatedBy?.fullName || 'N/A' },
  ];

  if (loading) {
    return <Loader />;
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Resource Dashboard</h1>
          <p className="text-gray-500 text-sm mt-1">Overview of Somalia's natural resource inventory and active projects.</p>
        </div>
        <div className="text-sm text-gray-500 bg-white px-3 py-1.5 rounded-md border border-gray-200">
          {new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <DashboardCard 
          title="Total Resources" 
          value={stats.resources} 
          icon={Box} 
          colorClass="bg-blue-50 text-blue-600"
          trend="up"
          trendValue="+4.2%"
          className="border-t-4 border-t-blue-500"
        />
        <DashboardCard 
          title="Categories" 
          value={stats.categories} 
          icon={Layers} 
          colorClass="bg-[#0c4a34]/10 text-[#0c4a34]"
          trend="neutral"
          trendValue="Stable"
          className="border-t-4 border-t-[#0c4a34]"
        />
        <DashboardCard 
          title="Active Projects" 
          value={stats.projects} 
          icon={Briefcase} 
          colorClass="bg-yellow-50 text-yellow-600"
          trend="up"
          trendValue="12 New"
          className="border-t-4 border-t-yellow-500"
        />
        <DashboardCard 
          title="Total Reports" 
          value={stats.reports} 
          icon={FileText} 
          colorClass="bg-purple-50 text-purple-600"
          className="border-t-4 border-t-purple-500"
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-1 bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Resource Distribution</h2>
          <div className="h-64">
            {chartData.length > 0 ? (
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={chartData}
                    cx="50%"
                    cy="50%"
                    innerRadius={60}
                    outerRadius={80}
                    paddingAngle={5}
                    dataKey="value"
                  >
                    {chartData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip />
                  <Legend verticalAlign="bottom" height={36}/>
                </PieChart>
              </ResponsiveContainer>
            ) : (
              <div className="flex h-full items-center justify-center text-gray-400 text-sm">
                No data available for chart
              </div>
            )}
          </div>
        </div>

        <div className="lg:col-span-2 bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden flex flex-col">
          <div className="p-6 border-b border-gray-100 flex justify-between items-center">
            <h2 className="text-lg font-semibold text-gray-900">Recent Reports</h2>
          </div>
          <div className="flex-1 p-0">
             <Table 
                columns={reportColumns} 
                data={recentReports} 
                isLoading={loading}
                emptyMessage="No reports have been generated yet."
             />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
