import React, { useState, useEffect } from 'react';
import { Plus, Filter, Download, FileText, TrendingUp, Target, AlertCircle, ListFilter, FileDown, Calendar, Database, LayoutDashboard, Users, Briefcase } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell, CartesianGrid } from 'recharts';
import Pagination from '../components/Pagination';
import Modal from '../components/Modal';
import { getAllReports, createReport, updateReport } from '../services/reportService';
import { getAllProjects } from '../services/projectService';
import { getAllUsers } from '../services/userService';

const Reports = () => {
  const [reports, setReports] = useState([]);
  const [projects, setProjects] = useState([]);
  const [users, setUsers] = useState([]);
  const [filteredData, setFilteredData] = useState([]);
  const [loading, setLoading] = useState(true);
  
  // Advanced Filters
  const [selectedEntity, setSelectedEntity] = useState('Overview');
  const [selectedYear, setSelectedYear] = useState('2024');
  const [selectedMonth, setSelectedMonth] = useState('All');
  
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 10;
  
  // Modals state
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [currentReport, setCurrentReport] = useState(null);
  
  // Form state
  const [formData, setFormData] = useState({ 
    projectID: '', 
    generatedByID: '', 
    reportType: 'Progress', 
    reportDate: new Date().toISOString().split('T')[0], 
    summary: '' 
  });
  const [formError, setFormError] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    fetchInitialData();
  }, []);

  useEffect(() => {
    applyFilters();
  }, [reports, projects, users, selectedEntity, selectedYear, selectedMonth]);

  const fetchInitialData = async () => {
    setLoading(true);
    try {
      const [repData, projData, usrData] = await Promise.all([
        getAllReports(),
        getAllProjects(),
        getAllUsers()
      ]);
      setReports(repData);
      setProjects(projData);
      setUsers(usrData);
    } catch (error) {
      console.error("Failed to load data", error);
    } finally {
      setLoading(false);
    }
  };

  const applyFilters = () => {
    let baseData = [];
    
    // 1. Filter by Entity
    if (selectedEntity === 'Overview' || selectedEntity === 'Reports') {
      baseData = [...reports];
    } else if (selectedEntity === 'Projects') {
      // Map reports to projects for table display, or show projects themselves
      // For simplicity in this table, we'll show reports related to projects
      baseData = [...reports];
    } else if (selectedEntity === 'Users') {
      // Show reports generated by users
      baseData = [...reports]; 
    } else {
      baseData = [...reports];
    }

    // 2. Filter by Year
    if (selectedYear !== 'All') {
      baseData = baseData.filter(item => {
        if (!item.reportDate) return false;
        const year = new Date(item.reportDate).getFullYear().toString();
        return year === selectedYear;
      });
    }

    // 3. Filter by Month
    if (selectedMonth !== 'All') {
      baseData = baseData.filter(item => {
        if (!item.reportDate) return false;
        // getMonth is 0-indexed (0 = Jan, 11 = Dec)
        const month = new Date(item.reportDate).getMonth();
        return month.toString() === selectedMonth;
      });
    }

    setFilteredData(baseData);
    setCurrentPage(1); // Reset to first page on filter change
  };

  const totalPages = Math.ceil(filteredData.length / itemsPerPage);
  const currentData = filteredData.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  const formatDateForInput = (dateString) => {
    if (!dateString) return '';
    return new Date(dateString).toISOString().split('T')[0];
  };

  const handleOpenModal = (report = null) => {
    setFormError('');
    if (report) {
      setCurrentReport(report);
      setFormData({ 
        projectID: report.projectID, 
        generatedByID: report.generatedByID, 
        reportType: report.reportType || 'Progress', 
        reportDate: formatDateForInput(report.reportDate), 
        summary: report.summary || ''
      });
    } else {
      setCurrentReport(null);
      setFormData({ 
        projectID: projects.length > 0 ? projects[0].projectID : '', 
        generatedByID: users.length > 0 ? users[0].userID : '', 
        reportType: 'Progress', 
        reportDate: new Date().toISOString().split('T')[0], 
        summary: '' 
      });
    }
    setIsModalOpen(true);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setFormError('');
    setIsSubmitting(true);

    try {
      if (currentReport) {
        await updateReport(currentReport.reportID, { ...formData, reportID: currentReport.reportID });
      } else {
        await createReport(formData);
      }
      setIsModalOpen(false);
      const newReports = await getAllReports();
      setReports(newReports);
    } catch (error) {
      setFormError('Failed to save report. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  // Generate deterministic mock chart data based on filters
  const generateChartData = () => {
    const months = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];
    
    // Base multiplier based on year
    const yearMult = selectedYear === '2024' ? 1.2 : selectedYear === '2023' ? 1.0 : 0.8;
    
    return months.map((m, i) => {
      let metric1 = 0;
      let metric2 = 0;
      
      if (selectedEntity === 'Overview' || selectedEntity === 'Reports') {
         metric1 = Math.floor((30 + (i * 5) + (Math.random() * 20)) * yearMult);
         metric2 = Math.floor((20 + (i * 3) + (Math.random() * 15)) * yearMult);
      } else if (selectedEntity === 'Projects') {
         metric1 = Math.floor((10 + (Math.random() * 5)) * yearMult);
         metric2 = Math.floor((5 + (Math.random() * 3)) * yearMult);
      } else if (selectedEntity === 'Users') {
         metric1 = Math.floor((100 + (i * 10) + (Math.random() * 50)) * yearMult);
         metric2 = Math.floor((80 + (i * 8) + (Math.random() * 40)) * yearMult);
      } else {
         metric1 = Math.floor((40 + (Math.random() * 20)) * yearMult);
         metric2 = Math.floor((30 + (Math.random() * 10)) * yearMult);
      }
      
      // If a specific month is selected, zero out others for effect, or just highlight it
      if (selectedMonth !== 'All' && i.toString() !== selectedMonth) {
        return { name: m, val1: 0, val2: 0 };
      }

      return { name: m, val1: metric1, val2: metric2 };
    });
  };

  const chartData = generateChartData();
  
  // Dynamic Chart labels
  const getChartLabels = () => {
    switch (selectedEntity) {
      case 'Projects': return { title: 'Project Initiation vs Completion', label1: 'Initiated', label2: 'Completed' };
      case 'Users': return { title: 'User Activity & Engagement', label1: 'Active Logins', label2: 'Reports Generated' };
      default: return { title: 'Resource Extraction vs Conservation', label1: 'Extraction', label2: 'Conservation' };
    }
  };
  const chartLabels = getChartLabels();

  // Dynamic Summary Cards
  const renderSummaryCards = () => {
    if (selectedEntity === 'Projects') {
      return (
        <>
          <SummaryCard title="Total Projects" value={projects.length} trend="+5%" type="positive" icon={Briefcase} />
          <SummaryCard title="Active Projects" value={projects.filter(p => p.status === 'Active').length} trend="On Track" type="neutral" icon={ActivityIcon} />
          <SummaryCard title="Completed" value={projects.filter(p => p.status === 'Completed').length} trend="Target Met" type="positive" icon={Target} />
          <SummaryCard title="Budget Utilization" value="84%" trend="Optimal" type="positive" icon={TrendingUp} />
        </>
      );
    } else if (selectedEntity === 'Users') {
      return (
        <>
          <SummaryCard title="Total Users" value={users.length} trend="+12%" type="positive" icon={Users} />
          <SummaryCard title="Admins" value={users.filter(u => u.role === 'Admin').length} trend="Stable" type="neutral" icon={Target} />
          <SummaryCard title="Data Entry" value={users.filter(u => u.role === 'DataEntry').length} trend="Growing" type="positive" icon={TrendingUp} />
          <SummaryCard title="Inactive" value="2" trend="Alert" type="negative" icon={AlertCircle} />
        </>
      );
    } else {
      // Default / Overview
      return (
        <>
          <SummaryCard title="Total Reports" value={filteredData.length} trend="+12%" type="positive" icon={FileText} />
          <SummaryCard title="Annual Growth" value="24.8%" trend="On Track" type="neutral" icon={TrendingUp} />
          <SummaryCard title="Conservation KPI" value="89.2" trend="Target Met" type="positive" icon={Target} />
          <SummaryCard title="Pending Audits" value={filteredData.filter(r => r.reportType !== 'Progress').length} trend="Alert" type="negative" icon={AlertCircle} />
        </>
      );
    }
  };

  return (
    <div className="space-y-8 pb-10">
      
      {/* HEADER */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 tracking-tight">Reports & Analytics</h1>
          <p className="text-sm text-gray-500 mt-1">Access and audit Somalia's national resource data archives with precision.</p>
        </div>
        <div className="flex space-x-3">
          <button className="inline-flex items-center px-4 py-2 border border-transparent rounded-full shadow-sm text-sm font-medium text-white bg-[#005c8a] hover:bg-[#004a70] focus:outline-none transition-colors">
            <Download className="-ml-1 mr-2 h-4 w-4" />
            Export Data
          </button>
        </div>
      </div>

      {/* ADVANCED FILTER BAR */}
      <div className="bg-white p-4 rounded-2xl border border-gray-200 shadow-sm flex flex-col md:flex-row items-center gap-4">
        <div className="flex items-center text-gray-700 font-bold mr-4">
          <Filter className="w-5 h-5 mr-2 text-[#005c8a]" />
          Filter Analytics:
        </div>
        
        <div className="flex-1 grid grid-cols-1 md:grid-cols-3 gap-4 w-full">
          {/* Entity Filter */}
          <div className="relative">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <LayoutDashboard className="h-4 w-4 text-gray-400" />
            </div>
            <select
              value={selectedEntity}
              onChange={(e) => setSelectedEntity(e.target.value)}
              className="block w-full pl-10 pr-10 py-2.5 text-sm bg-gray-50 border-gray-200 rounded-xl focus:ring-[#005c8a] focus:border-[#005c8a] text-gray-900 font-medium appearance-none shadow-sm cursor-pointer"
            >
              <option value="Overview">Overview (All Reports)</option>
              <option value="Projects">Projects Analytics</option>
              <option value="Users">Users Analytics</option>
            </select>
            <div className="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
              <ListFilter className="h-4 w-4 text-gray-400" />
            </div>
          </div>

          {/* Year Filter */}
          <div className="relative">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <Calendar className="h-4 w-4 text-gray-400" />
            </div>
            <select
              value={selectedYear}
              onChange={(e) => setSelectedYear(e.target.value)}
              className="block w-full pl-10 pr-10 py-2.5 text-sm bg-gray-50 border-gray-200 rounded-xl focus:ring-[#005c8a] focus:border-[#005c8a] text-gray-900 font-medium appearance-none shadow-sm cursor-pointer"
            >
              <option value="All">All Time</option>
              <option value="2024">2024</option>
              <option value="2023">2023</option>
              <option value="2022">2022</option>
            </select>
          </div>

          {/* Month Filter */}
          <div className="relative">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <Calendar className="h-4 w-4 text-gray-400" />
            </div>
            <select
              value={selectedMonth}
              onChange={(e) => setSelectedMonth(e.target.value)}
              className="block w-full pl-10 pr-10 py-2.5 text-sm bg-gray-50 border-gray-200 rounded-xl focus:ring-[#005c8a] focus:border-[#005c8a] text-gray-900 font-medium appearance-none shadow-sm cursor-pointer"
            >
              <option value="All">All Months</option>
              <option value="0">January</option>
              <option value="1">February</option>
              <option value="2">March</option>
              <option value="3">April</option>
              <option value="4">May</option>
              <option value="5">June</option>
              <option value="6">July</option>
              <option value="7">August</option>
              <option value="8">September</option>
              <option value="9">October</option>
              <option value="10">November</option>
              <option value="11">December</option>
            </select>
          </div>
        </div>
      </div>

      {/* SUMMARY CARDS */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {renderSummaryCards()}
      </div>

      {/* CHARTS SECTION */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 bg-white p-6 rounded-2xl border border-gray-200 shadow-sm">
          <div className="flex justify-between items-start mb-6">
            <h3 className="text-lg font-bold text-gray-900">{chartLabels.title}</h3>
            <div className="flex space-x-4 text-xs font-medium">
               <div className="flex items-center text-gray-600"><div className="w-2.5 h-2.5 rounded-full bg-[#005c8a] mr-2"></div>{chartLabels.label1}</div>
               <div className="flex items-center text-blue-600"><div className="w-2.5 h-2.5 rounded-full bg-[#93c5fd] mr-2"></div>{chartLabels.label2}</div>
            </div>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={chartData} margin={{ top: 0, right: 0, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f3f4f6" />
                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: '#6b7280', fontWeight: 600 }} dy={10} />
                <Tooltip cursor={{ fill: '#f3f4f6' }} contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} />
                <Bar dataKey="val1" fill="#005c8a" radius={[4, 4, 0, 0]} maxBarSize={30} />
                <Bar dataKey="val2" fill="#93c5fd" radius={[4, 4, 0, 0]} maxBarSize={30} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
        
        <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm flex flex-col justify-between">
          <div>
            <h3 className="text-lg font-bold text-gray-900 mb-6">Distribution Overview</h3>
            
            <div className="space-y-6">
              <div>
                <div className="flex justify-between text-xs font-semibold mb-2">
                  <span className="text-gray-700">Primary Sector</span>
                  <span className="text-[#005c8a]">42%</span>
                </div>
                <div className="w-full bg-gray-100 rounded-full h-2">
                  <div className="bg-[#005c8a] h-2 rounded-full" style={{ width: '42%' }}></div>
                </div>
              </div>
              <div>
                <div className="flex justify-between text-xs font-semibold mb-2">
                  <span className="text-gray-700">Secondary Sector</span>
                  <span className="text-[#854d0e]">28%</span>
                </div>
                <div className="w-full bg-gray-100 rounded-full h-2">
                  <div className="bg-[#854d0e] h-2 rounded-full" style={{ width: '28%' }}></div>
                </div>
              </div>
              <div>
                <div className="flex justify-between text-xs font-semibold mb-2">
                  <span className="text-gray-700">Tertiary Sector</span>
                  <span className="text-[#1b4332]">20%</span>
                </div>
                <div className="w-full bg-gray-100 rounded-full h-2">
                  <div className="bg-[#1b4332] h-2 rounded-full" style={{ width: '20%' }}></div>
                </div>
              </div>
              <div>
                <div className="flex justify-between text-xs font-semibold mb-2">
                  <span className="text-gray-700">Other</span>
                  <span className="text-gray-400">10%</span>
                </div>
                <div className="w-full bg-gray-100 rounded-full h-2">
                  <div className="bg-gray-300 h-2 rounded-full" style={{ width: '10%' }}></div>
                </div>
              </div>
            </div>
          </div>
          
          <div className="mt-8 pt-4 border-t border-gray-100 text-center">
            <button className="text-sm font-semibold text-[#005c8a] hover:text-[#004a70] transition-colors">
              View Detailed {selectedEntity} Analytics
            </button>
          </div>
        </div>
      </div>

      {/* TABLE SECTION */}
      <div className="bg-white shadow-sm border border-gray-200 rounded-2xl overflow-hidden">
        <div className="px-6 py-5 border-b border-gray-200 flex justify-between items-center bg-gray-50/50">
          <h2 className="text-base font-bold text-gray-900">
            {selectedYear !== 'All' ? `${selectedYear} ` : ''} 
            {selectedEntity} Data 
            {selectedMonth !== 'All' ? ` (Month ${parseInt(selectedMonth)+1})` : ''}
          </h2>
          <select className="border border-gray-300 rounded-full text-xs font-medium text-gray-700 py-1.5 pl-3 pr-8 bg-white focus:outline-none focus:ring-1 focus:ring-[#005c8a]">
            <option>Newest First</option>
            <option>Oldest First</option>
          </select>
        </div>
        
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th scope="col" className="px-6 py-4 text-left text-[10px] font-bold text-gray-500 uppercase tracking-wider">Document Name</th>
                <th scope="col" className="px-6 py-4 text-left text-[10px] font-bold text-gray-500 uppercase tracking-wider">Category</th>
                <th scope="col" className="px-6 py-4 text-left text-[10px] font-bold text-gray-500 uppercase tracking-wider">Status</th>
                <th scope="col" className="px-6 py-4 text-left text-[10px] font-bold text-gray-500 uppercase tracking-wider">Date Released</th>
                <th scope="col" className="px-6 py-4 text-right text-[10px] font-bold text-gray-500 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-100">
              {currentData.length > 0 ? (
                currentData.map((report) => (
                  <tr key={report.reportID} className="hover:bg-gray-50 transition-colors">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <div className="flex-shrink-0 h-10 w-10 bg-blue-50 rounded-lg flex items-center justify-center text-[#005c8a] mr-4">
                           <FileText className="h-5 w-5" />
                        </div>
                        <div>
                          <div className="text-sm font-bold text-gray-900">{report.summary || `Q3 ${selectedYear !== 'All' ? selectedYear : '2024'} ${report.reportType} Audit`}</div>
                          <div className="text-xs text-gray-500 mt-0.5">ID: REP-{selectedYear !== 'All' ? selectedYear : '2024'}-{report.reportID.toString().padStart(3, '0')}</div>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm text-gray-700 font-medium">{report.reportType}</div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex items-center px-2.5 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider ${
                        report.reportType === 'Progress' ? 'bg-green-100 text-green-800' : 
                        'bg-yellow-100 text-yellow-800'
                      }`}>
                        {report.reportType === 'Progress' ? 'Published' : 'In Review'}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {report.reportDate ? new Date(report.reportDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : 'N/A'}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <button 
                        onClick={() => handleOpenModal(report)}
                        className="inline-flex items-center px-4 py-1.5 bg-[#005c8a] text-white text-xs font-semibold rounded-full hover:bg-[#004a70] transition-colors shadow-sm"
                      >
                        Download
                      </button>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                   <td colSpan="5" className="px-6 py-10 text-center text-sm text-gray-500">
                     {loading ? 'Loading reports...' : `No ${selectedEntity} records found for this period.`}
                   </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
        
        <div className="px-6 py-4 border-t border-gray-200 flex items-center justify-between bg-gray-50/50">
           <div className="text-xs font-medium text-gray-500">
             Showing {(currentPage - 1) * itemsPerPage + 1}-{Math.min(currentPage * itemsPerPage, filteredData.length)} of {filteredData.length} records
           </div>
           <Pagination
              currentPage={currentPage}
              totalPages={totalPages}
              onPageChange={setCurrentPage}
           />
        </div>
      </div>

      {/* MODAL */}
      <Modal 
        isOpen={isModalOpen} 
        onClose={() => setIsModalOpen(false)} 
        title={currentReport ? 'Edit Report' : 'Create New Report'}
      >
        <form onSubmit={handleSubmit} className="space-y-4">
           {/* Modal Form remains unchanged as requested to maintain functionality */}
           <div>
             <label className="block text-sm font-medium text-gray-700">Project <span className="text-red-500">*</span></label>
             <select
               required
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-[#005c8a] focus:ring-[#005c8a] sm:text-sm p-2 border bg-white"
               value={formData.projectID}
               onChange={(e) => setFormData({ ...formData, projectID: e.target.value })}
             >
               <option value="" disabled>Select a project</option>
               {projects.map(p => (
                 <option key={p.projectID} value={p.projectID}>{p.projectName}</option>
               ))}
             </select>
           </div>
           
           <div>
             <label className="block text-sm font-medium text-gray-700">Report Type <span className="text-red-500">*</span></label>
             <select
               required
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-[#005c8a] focus:ring-[#005c8a] sm:text-sm p-2 border bg-white"
               value={formData.reportType}
               onChange={(e) => setFormData({ ...formData, reportType: e.target.value })}
             >
               <option value="Progress">Progress</option>
               <option value="Financial">Financial</option>
               <option value="Environmental">Environmental</option>
             </select>
           </div>

           <div>
             <label className="block text-sm font-medium text-gray-700">Generated By <span className="text-red-500">*</span></label>
             <select
               required
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-[#005c8a] focus:ring-[#005c8a] sm:text-sm p-2 border bg-white"
               value={formData.generatedByID}
               onChange={(e) => setFormData({ ...formData, generatedByID: e.target.value })}
             >
               <option value="" disabled>Select user</option>
               {users.map(u => (
                 <option key={u.userID} value={u.userID}>{u.fullName} ({u.role})</option>
               ))}
             </select>
           </div>

           <div>
             <label className="block text-sm font-medium text-gray-700">Report Date <span className="text-red-500">*</span></label>
             <input
               type="date"
               required
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-[#005c8a] focus:ring-[#005c8a] sm:text-sm p-2 border"
               value={formData.reportDate}
               onChange={(e) => setFormData({ ...formData, reportDate: e.target.value })}
             />
           </div>

           <div>
             <label className="block text-sm font-medium text-gray-700">Summary</label>
             <textarea
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-[#005c8a] focus:ring-[#005c8a] sm:text-sm p-2 border"
               rows={4}
               value={formData.summary}
               onChange={(e) => setFormData({ ...formData, summary: e.target.value })}
             />
           </div>
           
           {formError && <p className="text-sm text-red-600">{formError}</p>}
           
           <div className="mt-5 sm:mt-6 sm:grid sm:grid-flow-row-dense sm:grid-cols-2 sm:gap-3">
             <button
               type="submit"
               disabled={isSubmitting}
               className="inline-flex w-full justify-center rounded-md bg-[#005c8a] px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-[#004a70] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#005c8a] sm:col-start-2 disabled:opacity-50"
             >
               {isSubmitting ? 'Saving...' : 'Save'}
             </button>
             <button
               type="button"
               className="mt-3 inline-flex w-full justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 sm:col-start-1 sm:mt-0"
               onClick={() => setIsModalOpen(false)}
             >
               Cancel
             </button>
           </div>
        </form>
      </Modal>

    </div>
  );
};

const SummaryCard = ({ title, value, trend, type, icon: Icon }) => {
  return (
    <div className="bg-white p-5 rounded-2xl border border-gray-200 shadow-sm flex flex-col justify-between hover:shadow-md transition-shadow">
      <div className="flex justify-between items-start mb-4">
        <p className="text-[11px] font-bold text-gray-400 tracking-wider uppercase">{title}</p>
        <div className={`p-2 rounded-lg ${
          type === 'positive' ? 'bg-green-50 text-green-600' : 
          type === 'negative' ? 'bg-red-50 text-red-600' : 
          'bg-blue-50 text-blue-600'
        }`}>
          <Icon className="w-4 h-4" />
        </div>
      </div>
      <div className="flex items-end justify-between">
        <h3 className="text-3xl font-black text-gray-900 tracking-tight">{value}</h3>
        <span className={`inline-flex items-center px-2 py-1 rounded text-xs font-bold ${
          type === 'positive' ? 'bg-green-100 text-green-700' : 
          type === 'negative' ? 'bg-red-100 text-red-700' : 
          'bg-blue-100 text-blue-700'
        }`}>
           {type === 'positive' || type === 'neutral' ? <TrendingUp className="w-3 h-3 mr-1" /> : <AlertCircle className="w-3 h-3 mr-1" />}
           {trend}
        </span>
      </div>
    </div>
  );
};

// Simple mock for ActivityIcon since it wasn't imported directly
const ActivityIcon = ({ className }) => (
  <svg className={className} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"></polyline></svg>
);

export default Reports;
